/* Minimal config.h for flutter_kokoro_tts Android build.
 * espeak-ng sources expect config.h (normally generated by autoconf).
 */
#ifndef CONFIG_H
#define CONFIG_H

#define PACKAGE_VERSION "1.52.0"
#define HAVE_STDINT_H 1
#define HAVE_MKSTEMP 1
/* Required for speech.c; otherwise PATH_ESPEAK_DATA expands to (int)PATHSEP in speech.h */
#define PATH_ESPEAK_DATA ""
/* Use <endian.h> (Android NDK provides it) */
#undef HAVE_SYS_ENDIAN_H

/* Phonemizer-only: disable audio output and optional features */
#define USE_ASYNC 0
#define USE_KLATT 1
#define USE_LIBPCAUDIO 0
#define USE_LIBSONIC 0
#define USE_MBROLA 0
#define USE_SPEECHPLAYER 0

#endif /* CONFIG_H */
